In [59]:
import pandas as pd

In [60]:
df = pd.read_csv(r'C:\Users\prabh\OneDrive\Documents\Lambton\Semester 2\Data Mining and Anaysis\date.txt')

In [61]:
df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23674 entries, 0 to 23673
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    23674 non-null  object
 1   Symbol  23674 non-null  object
 2   Open    23674 non-null  float64
 3   High    23674 non-null  float64
 4   Low     23674 non-null  float64
 5   Close   23674 non-null  float64
 6   Volume  23674 non-null  float64
dtypes: float64(5), object(2)
memory usage: 1.3+ MB

In [63]:
df.loc[0]['Date']

'2020-03-13 08-PM'

In [64]:
df['Date']

0        2020-03-13 08-PM
1        2020-03-13 07-PM
2        2020-03-13 06-PM
3        2020-03-13 05-PM
4        2020-03-13 04-PM
               ...
23669    2017-07-01 03-PM
23670    2017-07-01 02-PM
23671    2017-07-01 01-PM
23672    2017-07-01 12-PM
23673    2017-07-01 11-AM
Name: Date, Length: 23674, dtype: object

In [65]:
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d %I-%p')

In [66]:
df['Date']

0       2020-03-13 20:00:00
1       2020-03-13 19:00:00
2       2020-03-13 18:00:00
3       2020-03-13 17:00:00
4       2020-03-13 16:00:00
                ...
23669   2017-07-01 15:00:00
23670   2017-07-01 14:00:00
23671   2017-07-01 13:00:00
23672   2017-07-01 12:00:00
23673   2017-07-01 11:00:00
Name: Date, Length: 23674, dtype: datetime64[ns]

In [67]:
df.loc[0]["Date"].day_name()

'Friday'

In [68]:
df["Date"].dt.day_name()

0          Friday
1          Friday
2          Friday
3          Friday
4          Friday
           ...
23669    Saturday
23670    Saturday
23671    Saturday
23672    Saturday
23673    Saturday
Name: Date, Length: 23674, dtype: object

In [69]:
df['DayofWeek'] = df["Date"].dt.day_name()

In [70]:
df

,Date,Symbol,Open,High,Low,Close,Volume,DayofWeek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [71]:
df['Date'].min()

Timestamp('2017-07-01 11:00:00')

In [72]:
df['Date'].max()

Timestamp('2020-03-13 20:00:00')

In [73]:
df['Date'].max() - df['Date'].min()

Timedelta('986 days 09:00:00')

In [74]:
flt = df['Date'] >= '2020-03-13 19:00:00'
df[flt]

,Date,Symbol,Open,High,Low,Close,Volume,DayofWeek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday

In [75]:
flt = (df['Date'] <= '2020-03-13 19:00:00') & (df['Date'] >= '2020-03-13 11:00:00')
df[flt]

,Date,Symbol,Open,High,Low,Close,Volume,DayofWeek
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
5,2020-03-13 15:00:00,ETHUSD,128.39,128.90,116.06,124.85,7378976.00,Friday
6,2020-03-13 14:00:00,ETHUSD,134.03,137.90,125.50,128.39,3733916.89,Friday
7,2020-03-13 13:00:00,ETHUSD,131.35,140.95,128.99,134.03,9582732.93,Friday
8,2020-03-13 12:00:00,ETHUSD,128.93,134.60,126.95,131.35,3906590.52,Friday
9,2020-03-13 11:00:00,ETHUSD,132.60,133.17,126.01,128.93,3311080.29,Friday

In [76]:
flt = (df['Date'] >= pd.to_datetime('2019-01-18')) & (df['Date'] <= pd.to_datetime('2020-06-17'))
df1 = df[flt]

In [77]:
flt = (df['Date'] >= '2019-01-18') & (df['Date'] <= '2020-06-17')
df2 = df[flt]

In [78]:
df1.equals(df2)

True

In [79]:
df1.shape, df2.shape

((10101, 8), (10101, 8))

In [80]:
df.set_index('Date',inplace=True)

In [81]:
df

,Symbol,Open,High,Low,Close,Volume,DayofWeek
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...
2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [85]:
df['2020-1':'2020-2']  # Since now dates are considered as index

,Symbol,Open,High,Low,Close,Volume,DayofWeek
Date,,,,,,,
2020-02-29 23:00:00,ETHUSD,223.35,223.58,216.83,217.31,1927939.88,Saturday
2020-02-29 22:00:00,ETHUSD,223.48,223.59,222.14,223.35,535998.57,Saturday
2020-02-29 21:00:00,ETHUSD,224.63,225.14,222.74,223.48,561158.03,Saturday
2020-02-29 20:00:00,ETHUSD,225.31,225.33,223.50,224.63,511648.65,Saturday
2020-02-29 19:00:00,ETHUSD,225.09,225.85,223.87,225.31,1250856.20,Saturday
...,...,...,...,...,...,...,...
2020-01-01 04:00:00,ETHUSD,129.57,130.00,129.50,129.56,702786.82,Wednesday
2020-01-01 03:00:00,ETHUSD,130.37,130.44,129.38,129.57,496704.23,Wednesday
2020-01-01 02:00:00,ETHUSD,130.14,130.50,129.91,130.37,396315.72,Wednesday
2020-01-01 01:00:00,ETHUSD,128.34,130.14,128.32,130.14,635419.40,Wednesday
2020-01-01 00:00:00,ETHUSD,128.54,128.54,128.12,128.34,245119.91,Wednesday

In [89]:
df['2020-1':'2020-2']['High'].mean(), df['2020-1':'2020-2']['High'].max(), df['2020-1':'2020-2']['High'].min()

(196.43905555555554, 290.0, 126.65)